# Gemfile
source 'http://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'slim'

gem 'recursive-open-struct'

gem 'pry'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'rubocop'
  gem 'capybara'
  gem 'cucumber'
  gem 'selenium-webdriver'
end