require 'rspec/core/rake_task'
require 'rubocop/rake_task'

task :default => [:spec, :rubocop]

desc 'Run RSpec on the tests'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '-fd'
end

desc 'Run RuboCop on the lib directory'
RuboCop::RakeTask.new(:rubocop) do |task|
  task.patterns = ['lib/**/*.rb', 'spec/**/*.rb']
  # only show the files with failures
  #task.formatters = ['files']
  # don't abort rake on failure
  task.fail_on_error = false
end

